. $HOME/bin/env_terraform_appdev.sh
export TF_VAR_compartment_ocid=ocid1.compartment.oc1..aaaaaaaa4vqn4n4z2qybg6waq6ve75tdxrkz4ibvknectgzbk3ujbxcsbsfq
export TF_VAR_function_image_uri=fra.ocir.io/frsxwtjslf35/opensearch-tika-function-2253:tikaparser
export TF_VAR_tenancy_ocid=ocid1.tenancy.oc1..aaaaaaaa4wptnxymnypvjjltnejidchjhz6uimlhru7rdi5qb6qlnmrtgu3a
export TF_VAR_terraform_state_url=eu-frankfurt-1